services:
  memory-graph:
    build:
      context: .
      dockerfile: ./dockerfile

    environment:
      DATABASE_URL: ${DATABASE_URL}
      AZURE_ENDPOINT: ${AZURE_ENDPOINT}
      AZURE_API_VERSION: ${AZURE_API_VERSION}
      AZURE_API_KEY: ${AZURE_API_KEY}

    restart: always
